### PR TITLE
Code improvements and optimization

### PR DESCRIPTION
**Pull request by FoxNeo**
Hi.

this is a pull request with improvements in your code.

Best regards
Miguel

### CODE REVIEW

**Comment by mbaykara** [comment]
Did you build the project before PR? It's not building.
update: building but crashing

**Comment by FoxNeo** [comment]
> Did you build the project before PR? It's not building. update: building but crashing

I build it with:
`mvn package`
```
[INFO] --- spring-boot-maven-plugin:2.2.1.RELEASE:repackage (repackage) @ kubernetes-configmap-reload ---
[INFO] Replacing main artifact with repackaged archive
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.062 s
[INFO] Finished at: 2021-10-08T00:59:34+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by mbaykara** [comment]
> > Did you build the project before PR? It's not building. update: building but crashing
> 
> I build it with: `mvn package`
> 
> ```
> [INFO] --- spring-boot-maven-plugin:2.2.1.RELEASE:repackage (repackage) @ kubernetes-configmap-reload ---
> [INFO] Replacing main artifact with repackaged archive
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  8.062 s
> [INFO] Finished at: 2021-10-08T00:59:34+02:00
> [INFO] ------------------------------------------------------------------------
> ```

but the app is crashing

**Comment by FoxNeo** [comment]
> > > Did you build the project before PR? It's not building. update: building but crashing
> > 
> > 
> > I build it with: `mvn package`
> > ```
> > [INFO] --- spring-boot-maven-plugin:2.2.1.RELEASE:repackage (repackage) @ kubernetes-configmap-reload ---
> > [INFO] Replacing main artifact with repackaged archive
> > [INFO] ------------------------------------------------------------------------
> > [INFO] BUILD SUCCESS
> > [INFO] ------------------------------------------------------------------------
> > [INFO] Total time:  8.062 s
> > [INFO] Finished at: 2021-10-08T00:59:34+02:00
> > [INFO] ------------------------------------------------------------------------
> > ```
> 
> but the app is crashing

It was the missed dependency now it should run
mvn spring-boot:run

**Pull request merged**
